repos:
  - repo: local
    hooks:
      - id: lint-spellcheck
        name: Spellcheck
        entry: cspell lint --no-progress --gitignore
        language: system
        files: \.(md|mdx)$
        pass_filenames: true
        description: "Runs spellcheck on markdown files"
        fail_fast: true

      - id: shellcheck
        name: Shellcheck
        entry: shellcheck
        language: system
        files: ^packages/(nix|installer|infrastructure)/.*\.sh$
        pass_filenames: true
        description: "Runs shellcheck on shell scripts"
        fail_fast: true

      - id: shellfmt
        name: Shell Format
        entry: shfmt --diff -i 2
        language: system
        files: ^packages/(nix|installer|infrastructure)/.*\.sh$
        pass_filenames: true
        description: "Runs shfmt on shell scripts"
        fail_fast: true

      - id: nixfmt
        name: Nix Format
        entry: nixfmt -c
        language: system
        files: ^packages/(nix|cli)/.*\.nix$
        pass_filenames: true
        description: "Runs nixfmt on Nix files"
        fail_fast: true

      - id: hcl-fmt
        name: HCL Format
        entry: terragrunt hclfmt --terragrunt-check --terragrunt-diff --terragrunt-hclfmt-file
        language: system
        files: ^packages/cli/.*\.hcl$
        pass_filenames: true
        description: "Runs hclfmt on HCL files"
        fail_fast: true

      - id: tf-fmt
        name: Tofu Format
        entry: tofu fmt -diff -check
        language: system
        files: ^packages/infrastructure/.*\.tf$
        pass_filenames: true
        description: "Runs tofu fmt on the infrastructure code"
        fail_fast: false

      - id: typecheck-website
        name: Typecheck Website
        entry: precommit-typecheck-website
        language: system
        files: ^packages/website/
        pass_filenames: false
        description: "Runs a typecheck on the website code"
        fail_fast: true

      - id: lint-website
        name: Lint Website
        entry: precommit-lint-website
        language: system
        files: ^packages/website/src/.*\.(ts|tsx|astro)$
        pass_filenames: true
        description: "Runs linting for the website code"
        fail_fast: true

      - id: typecheck-cli
        name: Typecheck CLI
        entry: precommit-typecheck-cli
        language: system
        files: ^packages/cli/
        pass_filenames: false
        description: "Runs a typecheck on the CLI code"
        fail_fast: true

      - id: lint-cli
        name: Lint CLI
        entry: precommit-lint-cli
        language: system
        files: ^packages/cli/.*\.ts$
        pass_filenames: true
        description: "Runs linting for the CLI code"
        fail_fast: true

      - id: generate-tf-reference
        name: Generate Terraform Reference
        entry: precommit-generate-tf-reference
        language: system
        files: ^packages/infrastructure/[^/]+/
        pass_filenames: true
        description: "Generates terraform reference docs for changed modules"
        fail_fast: false
